version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
  build:
    commands:
      - npm install
      - npm run build
artifacts:
  files:
    - '**/*'
    - appspec.yml
  base-directory: dist  
